#!/bin/bash
#
# Reports drift in the extracted vendor blob tree.
#
# vendor/nothing/frogger/ is not a git repo and not a repo project, yet
# frogger-vendor.mk copies files straight out of it into the image. Nothing in
# the build compares it against anything, so a laptop and a build server can
# hold different blobs and both build successfully. They diverged by about
# thirty files once, camera blobs among them, and nothing surfaced it.
#
# docs/data/vendor-blobs.sha1 is the reference. This checks the tree against it.
#
#   (no argument)  names and sizes only. Instant, and what BoardConfig.mk runs.
#   --full         also verifies sha1. About a minute over 1.01 GB.
#   --generate     rewrites the manifest from the tree. Run after re-extracting.
#
# Reports on stderr and says nothing when the tree matches, because it runs from
# BoardConfig.mk on every invocation and make parses this script's stdout as
# makefile text.
#
# It does not fail the build. Drift is loud but not always wrong -- a legitimate
# re-extraction produces it until the manifest is regenerated -- and a config
# time failure would block every targeted build until someone noticed. If drift
# ever reaches an image, make the final exit non-zero and emit $(error) instead.
set -euo pipefail

# Resolved through any symlink: ~/bin entries point here, and dirname on the
# link would give the link's directory, making $top / -- where cd succeeds and
# the failure only surfaces later, somewhere else.
here="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"
top="${ANDROID_BUILD_TOP:-$(cd "$here/../../../.." && pwd)}"
[ -f "$top/build/envsetup.sh" ] || { echo "not an Android tree: $top" >&2; exit 1; }

tree="$top/vendor/nothing/frogger"
manifest="$here/../docs/data/vendor-blobs.sha1"
mode="${1:-fast}"

# A checkout that has never been extracted is not drift. Say so once and stop.
[ -d "$tree" ] || { echo "vendor-blob-guard: $tree absent, skipping" >&2; exit 0; }

if [ "$mode" = "--generate" ]; then
    cd "$tree"
    {
        echo "# sha1  size  path -- generated by device/nothing/frogger/tools/vendor-blob-guard.sh --generate"
        echo "# Regenerate after any re-extraction. Do not hand-edit."
        find . -type f -printf "%s %p\n" | sort -k2 |
            while read -r sz path; do
                printf '%s %s %s\n' "$(sha1sum "$path" | cut -d' ' -f1)" "$sz" "$path"
            done
    } > "$manifest"
    echo "vendor-blob-guard: wrote $(grep -c '^[^#]' "$manifest") entries to $manifest" >&2
    exit 0
fi

[ -f "$manifest" ] || { echo "vendor-blob-guard: no manifest at $manifest" >&2; exit 0; }

want=$(mktemp); have=$(mktemp)
trap 'rm -f "$want" "$have"' EXIT

grep -v '^#' "$manifest" | awk '{print $2" "$3}' | sort -k2 > "$want"
( cd "$tree" && find . -type f -printf "%s %p\n" | sort -k2 ) > "$have"

if ! diff -q "$want" "$have" >/dev/null; then
    {
        echo "vendor-blob-guard: the blob tree does not match the manifest."
        # Every pipeline below needs its status swallowed or the script dies
        # mid-report and the hint at the end never prints. Two ways it fails
        # under `set -o pipefail`: diff exits 1 whenever files differ, which is
        # the only case that reaches here, and `head -40` closes the pipe on a
        # long list so upstream takes SIGPIPE. Each `|| true` is load-bearing.
        { diff "$want" "$have" || true; } | grep '^[<>]' |
            awk '$1=="<"{print "  missing or resized: "$3} $1==">"{print "  added or resized:   "$3}' |
            sort -u | head -40 || true
        n=$({ diff "$want" "$have" || true; } | grep -c '^[<>]' || true)
        if [ "$n" -gt 40 ]; then echo "  ... $n differing lines in total"; fi
        echo "  Re-extract, or regenerate with tools/vendor-blob-guard.sh --generate"
    } >&2
    exit 0
fi

[ "$mode" = "--full" ] || exit 0

cd "$tree"
bad=$(grep -v '^#' "$manifest" | awk '{print $1"  "$3}' | sha1sum -c --quiet 2>&1 || true)
if [ -n "$bad" ]; then
    { echo "vendor-blob-guard: contents differ where names and sizes match:"; echo "$bad" | head -20; } >&2
else
    echo "vendor-blob-guard: $(grep -c '^[^#]' "$manifest") files verified" >&2
fi
